version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - employee_network

  database:
    build: ./database
    volumes:
      - ./data:/data
    networks:
      - employee_network

networks:
  employee_network:
    driver: bridge
